import "./globals.css";
import { Inter } from "next/font/google";
import AuthContextProviderWrapper from "./layouts/AuthContextProviderWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "K-Market Vandor Demo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className + " text-black"}>
        <AuthContextProviderWrapper>{children}</AuthContextProviderWrapper>
      </body>
    </html>
  );
}
